name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/drako-gaming/website:latest
    
    - name: Loging to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: SirRippovMaple
        password: ${{ secrets.PACKAGE_TOKEN }}

    - name: Push the Docker image
      run: docker push ghcr.io/drako-gaming/website:latest
